export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Shariq Khan",
  description: "Shariq Khan - Cybersecurity student at York University (expected 2028) & Full-Stack Developer. Building secure, scalable applications. Based in Toronto, Canada.",
  url: "https://shariqsafdarkhan.com",
  ogImage: "https://shariqsafdarkhan.com/og-image.jpg",
  keywords: [ //
    "Shariq Khan",
    "Shariq Safdar Khan", 
    "Shariq S. Khan",
    "Shariq Khan Developer",
    "Shariq Khan Toronto",
    "Shariq Khan York University",
    "Shariq Khan Cybersecurity",
    "Shariq Khan Full Stack Developer",
    "Shariq Khan Software Engineer",
    "Shariq Khan Portfolio",
    "Shariq Khan Web Developer",
    "Shariq Khan Canada",
    "Cybersecurity",
    "Full-Stack Developer",
    "Web Developer",
    "Software Engineer",
    "York University",
    "Toronto Developer",
    "Canadian Developer",
    "Portfolio",
    "Web Development",
    "Security",
    "Import Analyst",
    "Farrow",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "Node.js Developer",
    "Database Developer",
    "API Developer",
    "Frontend Developer",
    "Backend Developer"
  ],
  author: "Shariq Khan",
  creator: "Shariq Khan",
  publisher: "Shariq Khan",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://shariqsafdarkhan.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://shariqsafdarkhan.com",
    title: "Shariq Khan",
    description: "Shariq Khan - Cybersecurity student at York University (expected 2028) & Full-Stack Developer. Building secure, scalable applications. Based in Toronto, Canada.",
    siteName: "Shariq Khan Portfolio",
    images: [
      {
        url: "https://shariqsafdarkhan.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Shariq Khan | Full-Stack Developer & York University cybersecurity student (expected 2028)",
      },
    ],
  },
      twitter: {
      card: "summary_large_image",
      title: "Shariq Khan",
    description: "Shariq Khan - Cybersecurity student at York University (expected 2028) & Full-Stack Developer. Building secure, scalable applications. Based in Toronto, Canada.",
    images: ["https://shariqsafdarkhan.com/og-image.jpg"],
    creator: "@shariqsk",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  navItems: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Projects",
      href: "/projects",
    },
    {
      label: "Resume",
      href: "https://drive.google.com/file/d/1OR1LvVnBO5A61yTYNxE0aM3IxmpCDv4g/view?usp=sharing",
    },
    {
      label: "Contact",
      href: "/contact",
    },
  ],
  navMenuItems: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Projects",
      href: "/projects",
    },
    {
      label: "Resume",
      href: "https://drive.google.com/file/d/1OR1LvVnBO5A61yTYNxE0aM3IxmpCDv4g/view?usp=sharing",
    },
    {
      label: "Contact",
      href: "/contact",
    },
  ],
  links: {
    github: "https://github.com/shariqsk",
    linkedin: "https://www.linkedin.com/in/shariq-khan-430754217/",
    email: "mailto:contact@shariqsafdarkhan.com",
    phone: "",
    blog: "https://shariqsk.github.io/",
    resume: "https://drive.google.com/file/d/1OR1LvVnBO5A61yTYNxE0aM3IxmpCDv4g/view?usp=sharing",
  },
};
