export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Shariq Khan | Full-Stack Developer & Cybersecurity Expert",
  description: "Shariq Khan - Computer Security Student at York University & Full-Stack Developer. Expert in cybersecurity, web development, and building secure applications. Based in Toronto, Canada.",
  url: "https://shariqsafdarkhan.com",
  ogImage: "https://shariqsafdarkhan.com/og-image.jpg",
  keywords: [
    "Shariq Khan",
    "Shariq Safdar Khan", 
    "Shariq S. Khan",
    "Shariq Khan Developer",
    "Shariq Khan Toronto",
    "Shariq Khan York University",
    "Shariq Khan Cybersecurity",
    "Shariq Khan Full Stack Developer",
    "Shariq Khan Software Engineer",
    "Shariq Khan Portfolio",
    "Shariq Khan Web Developer",
    "Shariq Khan Canada",
    "Computer Security",
    "Cybersecurity",
    "Full-Stack Developer",
    "Web Developer",
    "Software Engineer",
    "York University",
    "Toronto Developer",
    "Canadian Developer",
    "Portfolio",
    "Web Development",
    "Security",
    "Import Analyst",
    "Farrow",
    "React Developer",
    "Next.js Developer",
    "TypeScript Developer",
    "Node.js Developer",
    "Database Developer",
    "API Developer",
    "Frontend Developer",
    "Backend Developer"
  ],
  author: "Shariq Khan",
  creator: "Shariq Khan",
  publisher: "Shariq Khan",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://shariqsafdarkhan.com"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://shariqsafdarkhan.com",
    title: "Shariq Khan | Full-Stack Developer & Cybersecurity Expert",
    description: "Shariq Khan - Computer Security Student at York University & Full-Stack Developer. Expert in cybersecurity, web development, and building secure applications. Based in Toronto, Canada.",
    siteName: "Shariq Khan Portfolio",
    images: [
      {
        url: "https://shariqsafdarkhan.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Shariq Khan | Full-Stack Developer & Cybersecurity Expert",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Shariq Khan | Full-Stack Developer & Cybersecurity Expert",
    description: "Shariq Khan - Computer Security Student at York University & Full-Stack Developer. Expert in cybersecurity, web development, and building secure applications. Based in Toronto, Canada.",
    images: ["https://shariqsafdarkhan.com/og-image.jpg"],
    creator: "@shariqsk",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  navItems: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Projects",
      href: "/projects",
    },
    {
      label: "Contact",
      href: "/contact",
    },
  ],
  navMenuItems: [
    {
      label: "Home",
      href: "/",
    },
    {
      label: "About",
      href: "/about",
    },
    {
      label: "Projects",
      href: "/projects",
    },
    {
      label: "Contact",
      href: "/contact",
    },
    {
      label: "Resume",
      href: "https://drive.google.com/file/d/1U9dGVpkArAHfgTKGVfEm_3nufE68Ea_L/view?usp=sharing",
    },
  ],
  links: {
    github: "https://github.com/shariqsk",
    linkedin: "https://www.linkedin.com/in/shariq-khan-430754217/",
    email: "mailto:contact@shariqsk.com",
    phone: "",
    blog: "https://shariqsk.github.io/",
    resume: "https://drive.google.com/file/d/1U9dGVpkArAHfgTKGVfEm_3nufE68Ea_L/view?usp=sharing",
  },
};
